/**
 * Volt UI CSS Generator
 * Generiert eine angepasste volt-ui.css mit den extrahierten Projekt-Tokens.
 * Die Volt-Architektur (Textur, Patterns, Glow) bleibt erhalten –
 * nur Farben und Fonts werden auf das Zielprojekt angepasst.
 */

import type { VoltTokenMapping } from "./themeAnalyzer";

/** Konvertiert Hex zu OKLCH-Näherung für Tailwind 4 */
function hexToOklch(hex: string): string {
  const r = parseInt(hex.slice(1, 3), 16) / 255;
  const g = parseInt(hex.slice(3, 5), 16) / 255;
  const b = parseInt(hex.slice(5, 7), 16) / 255;

  const L = 0.2126 * r + 0.7152 * g + 0.0722 * b;
  const lightness = Math.round(Math.pow(L, 0.43) * 100) / 100;

  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  const chroma = Math.round((max - min) * 0.4 * 100) / 100;

  let hue = 0;
  if (max !== min) {
    if (max === r) hue = ((g - b) / (max - min)) * 60;
    else if (max === g) hue = ((b - r) / (max - min)) * 60 + 120;
    else hue = ((r - g) / (max - min)) * 60 + 240;
    if (hue < 0) hue += 360;
  }

  return `oklch(${lightness} ${chroma} ${Math.round(hue)})`;
}

/** Berechnet Luminanz */
function getLuminance(hex: string): number {
  const r = parseInt(hex.slice(1, 3), 16) / 255;
  const g = parseInt(hex.slice(3, 5), 16) / 255;
  const b = parseInt(hex.slice(5, 7), 16) / 255;
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

/** Leicht aufgehellte Farbe für Hover-States */
function lighten(hex: string, amount = 0.1): string {
  const r = Math.min(255, parseInt(hex.slice(1, 3), 16) + Math.round(255 * amount));
  const g = Math.min(255, parseInt(hex.slice(3, 5), 16) + Math.round(255 * amount));
  const b = Math.min(255, parseInt(hex.slice(5, 7), 16) + Math.round(255 * amount));
  return `#${r.toString(16).padStart(2, "0")}${g.toString(16).padStart(2, "0")}${b.toString(16).padStart(2, "0")}`.toUpperCase();
}

/** Leicht abgedunkelte Farbe für Active-States */
function darken(hex: string, amount = 0.1): string {
  const r = Math.max(0, parseInt(hex.slice(1, 3), 16) - Math.round(255 * amount));
  const g = Math.max(0, parseInt(hex.slice(3, 5), 16) - Math.round(255 * amount));
  const b = Math.max(0, parseInt(hex.slice(5, 7), 16) - Math.round(255 * amount));
  return `#${r.toString(16).padStart(2, "0")}${g.toString(16).padStart(2, "0")}${b.toString(16).padStart(2, "0")}`.toUpperCase();
}

export function generateVoltCss(tokens: VoltTokenMapping, projectName = "Project"): string {
  const isDarkBg = getLuminance(tokens.background) < 0.3;
  const primaryOklch = hexToOklch(tokens.primary);
  const bgOklch = hexToOklch(tokens.background);
  const fgOklch = hexToOklch(tokens.foreground);
  const accentOklch = hexToOklch(tokens.accent);

  // Muted: leicht abgedunkelt/aufgehellt je nach Theme
  const mutedHex = isDarkBg ? lighten(tokens.background, 0.08) : darken(tokens.background, 0.05);
  const mutedOklch = hexToOklch(mutedHex);

  // Secondary: zwischen Background und Muted
  const secondaryHex = isDarkBg ? lighten(tokens.background, 0.04) : darken(tokens.background, 0.02);
  const secondaryOklch = hexToOklch(secondaryHex);

  // Border: sehr subtil
  const borderHex = isDarkBg ? lighten(tokens.background, 0.12) : darken(tokens.background, 0.1);
  const borderOklch = hexToOklch(borderHex);

  // Foreground auf Primary (Kontrast-Check)
  const primaryFg = getLuminance(tokens.primary) > 0.4 ? "#0A0A0A" : "#FFFFFF";

  // Google Fonts URL
  const displayFont = tokens.fontDisplay.replace(/ /g, "+");
  const bodyFont = tokens.fontBody.replace(/ /g, "+");
  const fontsUrl = `https://fonts.googleapis.com/css2?family=${displayFont}:wght@400;500;600;700;800;900&family=${bodyFont}:wght@300;400;500;600&family=JetBrains+Mono:wght@400;500&display=swap`;

  return `/**
 * volt-ui.css – Adapted for ${projectName}
 * Generated by Volt UI Theme Agent v2
 * Base: Volt UI Design System (Lime + Black)
 * Adapted: ${tokens.primary} primary · ${tokens.fontDisplay} display · ${tokens.fontBody} body
 *
 * Usage: <link rel="stylesheet" href="volt-ui.css">
 * Then use Volt-prefixed CSS variables in your project.
 */

/* ── Google Fonts ── */
@import url("${fontsUrl}");

/* ═══════════════════════════════════════════════════════════════════
   VOLT DESIGN TOKENS – Adapted for ${projectName}
   ═══════════════════════════════════════════════════════════════════ */

:root {
  /* ── Brand Colors ── */
  --volt-primary:          ${tokens.primary};
  --volt-primary-oklch:    ${primaryOklch};
  --volt-primary-fg:       ${primaryFg};
  --volt-primary-hover:    ${lighten(tokens.primary, 0.08)};
  --volt-primary-active:   ${darken(tokens.primary, 0.08)};

  --volt-accent:           ${tokens.accent};
  --volt-accent-oklch:     ${accentOklch};

  /* ── Semantic Colors ── */
  --volt-background:       ${tokens.background};
  --volt-background-oklch: ${bgOklch};
  --volt-foreground:       ${tokens.foreground};
  --volt-foreground-oklch: ${fgOklch};

  --volt-secondary:        ${secondaryHex};
  --volt-secondary-oklch:  ${secondaryOklch};
  --volt-muted:            ${mutedHex};
  --volt-muted-oklch:      ${mutedOklch};
  --volt-border:           ${borderHex};
  --volt-border-oklch:     ${borderOklch};

  /* ── Signal Colors (unverändert) ── */
  --volt-signal-positive:        #1A9E5A;
  --volt-signal-positive-light:  #E8F7EF;
  --volt-signal-positive-border: #A3D9BE;
  --volt-signal-positive-text:   #0D6B3D;

  --volt-signal-negative:        #E8402A;
  --volt-signal-negative-light:  #FDF0ED;
  --volt-signal-negative-border: #F5B8AE;
  --volt-signal-negative-text:   #9E2A1A;

  --volt-signal-neutral:         #6B7A9A;
  --volt-signal-neutral-light:   #F0F2F7;
  --volt-signal-neutral-border:  #C8CEDC;
  --volt-signal-neutral-text:    #4A5570;

  /* ── Typography ── */
  --volt-font-display: "${tokens.fontDisplay}", system-ui, sans-serif;
  --volt-font-body:    "${tokens.fontBody}", system-ui, sans-serif;
  --volt-font-mono:    "JetBrains Mono", "Fira Code", monospace;

  /* ── Spacing (8pt Grid) ── */
  --volt-space-1:  4px;
  --volt-space-2:  8px;
  --volt-space-3:  12px;
  --volt-space-4:  16px;
  --volt-space-6:  24px;
  --volt-space-8:  32px;
  --volt-space-10: 40px;
  --volt-space-12: 48px;
  --volt-space-16: 64px;
  --volt-space-20: 80px;

  /* ── Border Radius ── */
  --volt-radius-sm:   4px;
  --volt-radius-md:   ${tokens.borderRadius};
  --volt-radius-lg:   calc(${tokens.borderRadius} * 1.5);
  --volt-radius-xl:   calc(${tokens.borderRadius} * 2);
  --volt-radius-full: 9999px;

  /* ── Shadows ── */
  --volt-shadow-sm:  0 1px 2px rgba(0,0,0,0.06);
  --volt-shadow-md:  0 4px 12px rgba(0,0,0,0.10);
  --volt-shadow-lg:  0 8px 24px rgba(0,0,0,0.14);
  --volt-shadow-xl:  0 16px 48px rgba(0,0,0,0.18);

  /* ── Glow Effects ── */
  --volt-glow-primary: 0 0 20px ${tokens.primary}60, 0 0 40px ${tokens.primary}30;
  --volt-glow-accent:  0 0 20px ${tokens.accent}60, 0 0 40px ${tokens.accent}30;
}

/* ═══════════════════════════════════════════════════════════════════
   BASE STYLES
   ═══════════════════════════════════════════════════════════════════ */

.volt-base {
  font-family: var(--volt-font-body);
  background-color: var(--volt-background);
  color: var(--volt-foreground);
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

/* ═══════════════════════════════════════════════════════════════════
   TYPOGRAPHY
   ═══════════════════════════════════════════════════════════════════ */

.volt-display-xl { font-family: var(--volt-font-display); font-size: 3rem;   font-weight: 900; line-height: 1.05; letter-spacing: -0.03em; }
.volt-display-lg { font-family: var(--volt-font-display); font-size: 2.25rem; font-weight: 800; line-height: 1.1;  letter-spacing: -0.02em; }
.volt-display-md { font-family: var(--volt-font-display); font-size: 1.5rem;  font-weight: 700; line-height: 1.2;  letter-spacing: -0.01em; }
.volt-heading    { font-family: var(--volt-font-display); font-size: 1.25rem; font-weight: 600; line-height: 1.3; }
.volt-body       { font-family: var(--volt-font-body);    font-size: 1rem;    font-weight: 400; line-height: 1.6; }
.volt-body-sm    { font-family: var(--volt-font-body);    font-size: 0.875rem; font-weight: 400; line-height: 1.5; }
.volt-caption    { font-family: var(--volt-font-body);    font-size: 0.75rem;  font-weight: 500; line-height: 1.4; letter-spacing: 0.02em; }
.volt-mono       { font-family: var(--volt-font-mono);    font-size: 0.875rem; font-weight: 400; line-height: 1.6; }

/* ═══════════════════════════════════════════════════════════════════
   BUTTONS
   ═══════════════════════════════════════════════════════════════════ */

.volt-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: var(--volt-space-2);
  font-family: var(--volt-font-body);
  font-size: 0.875rem;
  font-weight: 600;
  border-radius: var(--volt-radius-md);
  border: 1.5px solid transparent;
  cursor: pointer;
  transition: all 0.15s ease;
  text-decoration: none;
  white-space: nowrap;
  padding: var(--volt-space-2) var(--volt-space-4);
}

.volt-btn-primary {
  background-color: var(--volt-primary);
  color: var(--volt-primary-fg);
  border-color: var(--volt-primary);
}
.volt-btn-primary:hover {
  background-color: var(--volt-primary-hover);
  border-color: var(--volt-primary-hover);
}
.volt-btn-primary:active {
  background-color: var(--volt-primary-active);
}

.volt-btn-outline {
  background-color: transparent;
  color: var(--volt-foreground);
  border-color: var(--volt-border);
}
.volt-btn-outline:hover {
  background-color: var(--volt-muted);
}

.volt-btn-ghost {
  background-color: transparent;
  color: var(--volt-foreground);
  border-color: transparent;
}
.volt-btn-ghost:hover {
  background-color: var(--volt-muted);
}

.volt-btn-sm { padding: var(--volt-space-1) var(--volt-space-3); font-size: 0.75rem; }
.volt-btn-lg { padding: var(--volt-space-3) var(--volt-space-6); font-size: 1rem; }

/* ═══════════════════════════════════════════════════════════════════
   CARDS
   ═══════════════════════════════════════════════════════════════════ */

.volt-card {
  background-color: var(--volt-background);
  border: 1px solid var(--volt-border);
  border-radius: var(--volt-radius-lg);
  padding: var(--volt-space-6);
  box-shadow: var(--volt-shadow-sm);
}

.volt-card-elevated {
  background-color: var(--volt-background);
  border-radius: var(--volt-radius-lg);
  padding: var(--volt-space-6);
  box-shadow: var(--volt-shadow-md);
}

.volt-card-glass {
  background-color: color-mix(in srgb, var(--volt-background) 65%, transparent);
  backdrop-filter: blur(16px);
  -webkit-backdrop-filter: blur(16px);
  border: 1px solid color-mix(in srgb, var(--volt-border) 50%, transparent);
  border-radius: var(--volt-radius-lg);
  padding: var(--volt-space-6);
}

/* ═══════════════════════════════════════════════════════════════════
   INPUTS
   ═══════════════════════════════════════════════════════════════════ */

.volt-input {
  width: 100%;
  font-family: var(--volt-font-body);
  font-size: 0.875rem;
  background-color: var(--volt-background);
  color: var(--volt-foreground);
  border: 1.5px solid var(--volt-border);
  border-radius: var(--volt-radius-md);
  padding: var(--volt-space-2) var(--volt-space-3);
  outline: none;
  transition: border-color 0.15s ease, box-shadow 0.15s ease;
}
.volt-input:focus {
  border-color: var(--volt-primary);
  box-shadow: 0 0 0 3px color-mix(in srgb, var(--volt-primary) 20%, transparent);
}
.volt-input::placeholder {
  color: color-mix(in srgb, var(--volt-foreground) 40%, transparent);
}

/* ═══════════════════════════════════════════════════════════════════
   BADGES
   ═══════════════════════════════════════════════════════════════════ */

.volt-badge {
  display: inline-flex;
  align-items: center;
  gap: var(--volt-space-1);
  font-family: var(--volt-font-body);
  font-size: 0.7rem;
  font-weight: 600;
  letter-spacing: 0.04em;
  text-transform: uppercase;
  padding: 2px var(--volt-space-2);
  border-radius: var(--volt-radius-full);
}

.volt-badge-primary {
  background-color: color-mix(in srgb, var(--volt-primary) 15%, transparent);
  color: var(--volt-primary);
  border: 1px solid color-mix(in srgb, var(--volt-primary) 30%, transparent);
}

.volt-badge-positive {
  background-color: var(--volt-signal-positive-light);
  color: var(--volt-signal-positive-text);
  border: 1px solid var(--volt-signal-positive-border);
}

.volt-badge-negative {
  background-color: var(--volt-signal-negative-light);
  color: var(--volt-signal-negative-text);
  border: 1px solid var(--volt-signal-negative-border);
}

.volt-badge-neutral {
  background-color: var(--volt-signal-neutral-light);
  color: var(--volt-signal-neutral-text);
  border: 1px solid var(--volt-signal-neutral-border);
}

/* ═══════════════════════════════════════════════════════════════════
   GEOMETRIC PATTERNS
   ═══════════════════════════════════════════════════════════════════ */

.volt-pattern-dots {
  background-image: radial-gradient(circle, var(--volt-border) 1.5px, transparent 1.5px);
  background-size: 20px 20px;
}

.volt-pattern-grid {
  background-image:
    linear-gradient(to right, var(--volt-border) 1px, transparent 1px),
    linear-gradient(to bottom, var(--volt-border) 1px, transparent 1px);
  background-size: 24px 24px;
}

.volt-pattern-diagonal {
  background-image: repeating-linear-gradient(
    45deg,
    var(--volt-border) 0,
    var(--volt-border) 1px,
    transparent 0,
    transparent 50%
  );
  background-size: 12px 12px;
}

.volt-pattern-cross {
  background-image:
    linear-gradient(to right, var(--volt-border) 1px, transparent 1px),
    linear-gradient(to bottom, var(--volt-border) 1px, transparent 1px);
  background-size: 16px 16px;
  background-position: center center;
}

/* ═══════════════════════════════════════════════════════════════════
   VOLT TEXTURE (SVG Noise Overlay)
   ═══════════════════════════════════════════════════════════════════ */

.volt-texture {
  position: relative;
}
.volt-texture::after {
  content: "";
  position: absolute;
  inset: 0;
  background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.75' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)'/%3E%3C/svg%3E");
  opacity: 0.035;
  pointer-events: none;
  border-radius: inherit;
}

/* ═══════════════════════════════════════════════════════════════════
   GLOW EFFECTS
   ═══════════════════════════════════════════════════════════════════ */

.volt-glow-primary { box-shadow: var(--volt-glow-primary); }
.volt-glow-accent  { box-shadow: var(--volt-glow-accent); }

/* ═══════════════════════════════════════════════════════════════════
   UTILITY CLASSES
   ═══════════════════════════════════════════════════════════════════ */

.volt-divider {
  border: none;
  border-top: 1px solid var(--volt-border);
  margin: var(--volt-space-4) 0;
}

.volt-surface {
  background-color: var(--volt-secondary);
  border-radius: var(--volt-radius-md);
  padding: var(--volt-space-4);
}

.volt-muted-text { color: color-mix(in srgb, var(--volt-foreground) 50%, transparent); }
.volt-primary-text { color: var(--volt-primary); }
.volt-accent-text { color: var(--volt-accent); }
`;
}
